### ISSUE TITLE
为什么我跑第一个例子控制台报错呢

### ISSUE THREAD

**Issue by zhaozhuoboy** [justjavac/parcel-example#1]
![qq 20171211085347](https://user-images.githubusercontent.com/15223986/33811704-5c9d2ae0-de51-11e7-8fa9-090c7dbfe06b.png)
![qq 20171211085358](https://user-images.githubusercontent.com/15223986/33811703-58af1b32-de51-11e7-92f1-6a4570e0db51.png)

**Comment by justjavac** [comment]
1. `git clone git@github.com:justjavac/parcel-example.git`
2. `cd parcel-example/react-helloworld/`
3. `yarn`
4. `yarn start`

**Comment by zhaozhuoboy** [comment]
@justjavac 是的  ，就是这样做的。我自己光写个html   js  都跑不起来。也不知道为啥

**Comment by justjavac** [comment]
查一下编译后的代码吧。

我的编译完后：

[parcel-example-react-helloworld.zip](https://github.com/justjavac/parcel-example/files/1546280/parcel-example-react-helloworld.zip)

**Comment by phobal** [comment]
@zhaozhuoboy 我也遇到了类似的问题。我将 Node 版本改成 v8,x 以上就 OK 了， 但是具体原因不清楚

**Comment by zhaozhuoboy** [comment]
@phobal 我的node 是 6.11.2 稳定版的，window系统  我还是不搞环境了，搞坏了就没法了哈哈，回家再试试

**Comment by zhaozhuoboy** [comment]
@phobal parcel官网有没有说明  node的版本呀 ？刚看了一下  node 稳定版都8.9了

**Comment by wqcstrong** [comment]
@zhaozhuoboy 我今天开始看文档跟着做，也发现了同样的问题，也同样是把node升级到8.x稳定版才解决的，可是具体为什么，官方没有给出说明，我也很迷惑、

**Comment by zhaozhuoboy** [comment]
@phobal   :ok_hand:  3Q

**Comment by zhaozhuoboy** [comment]
@wqcstrong 你们的英文真好
